name: "FUXA by Sevimuelli"
description: "Easy and Web-based Process Visualization (SCADA/HMI/Dashboard) software - now for Home Assistant"
version: "1.0.2"
url: "https://github.com/sevimuelli/HA-Addon-FUXA"
slug: "fuxa-slr"
webui: "http://[HOST]:[PORT:1881]/home"
panel_icon: mdi:dog
panel_title: FUXA
ingress: true
ingress_port: 1881
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
  - addons:rw
  - config:rw
startup: services
ports:
  1881/tcp: 1881
